# .github/workflows/docker-image.yml
name: 构建并推送 Docker 镜像

# 任何分支的 push 事件都会触发此工作流程
on:
  push:
    branches:
      - '**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 提取 Docker 元数据
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/dreamina-free-api
          tags: |
            # 为 git 分支事件启用 ref 类型的标签 (e.g. "main")
            type=ref,event=branch
            # 为 git 标签事件启用 ref 类型的标签 (e.g. "v1.0.0")
            type=ref,event=tag
            # 启用 sha 类型的标签 (e.g. "a1b2c3d")
            type=sha

      - name: 设置 Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: 登录到 Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: 构建并推送 Docker 镜像
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
          # 启用缓存以加快构建速度
          cache-from: type=gha
          cache-to: type=gha,mode=max
